In [1]:
#Module, package, Library
#Module - A single .py file ccontaining exucutable code, functions, classes
#package - A folder containing modules and an __init__.py file.
#Library - The library is having a collection of related functionality of codes that allows us to perform many tasks without writing code.
#Numpy - Numerical Python
#To use numpy we need to import tha numpy library
import numpy as np

#Creating an array      Syntax     arr_variable=np.array(list_variable)
#1D array

lst_1=[1,2,3,4,5]
arr_1=np.array(lst_1)
print(arr_1)

[1 2 3 4 5]


In [2]:
#2D Array
lst_2=[[1,2,3],[3,4,5],[5,6,7]]
arr_2=np.array(lst_2)
print(arr_2)

[[1 2 3]
 [3 4 5]
 [5 6 7]]


In [3]:
#3D array
lst_3=[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]
arr_3=np.array(lst_3)
print(arr_3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [4]:
#Dimension       arr_variable.ndim
#shape           arr_variable.shape
#size            arr_variable.size
print(arr_3.ndim)

print(arr_3.shape)

print(arr_3.size)

3
(2, 2, 3)
12


In [5]:
#np.zeros((shape)) - It creates an array of elements having value 0
arr_zero=np.zeros((2,3))
print(arr_zero)

[[0. 0. 0.]
 [0. 0. 0.]]


In [6]:
#np.ones((shape)) - It creates an array of the given shape where all elements are one
arr_ones=np.ones((3,3))

In [7]:
print(arr_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#np.full((shape),value) - It creates an array of the given shape where each elememts are same as the given value
arr_full=np.full((2,3),9)
print(arr_full)

[[9 9 9]
 [9 9 9]]


In [9]:
#np.eye(row_number) - It creates an array which is like Identity matrix
arr_identity=np.eye(3)
print(arr_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
#np.random.rand(shape) - It creates an array of random numbers between 0 and 1 of the given shape
arr_random=np.random.rand(2,3)
print(arr_random)

[[0.85895579 0.8990856  0.23293951]
 [0.57770864 0.62277327 0.2986406 ]]


In [11]:
#np.arange(start,stop,step_size) - This is similar with the range function in the loop
arr_range=np.arange(1,10,2)
print(arr_range)

[1 3 5 7 9]


In [12]:
#Mathematical operation on array - element wise mathematical operation
arr_1=np.array([[1,2,3],[4,5,6]])
print(arr_1)
print("---------------")
arr_2=np.array([[7,8,9],[10,11,12]])
print(arr_2)

[[1 2 3]
 [4 5 6]]
---------------
[[ 7  8  9]
 [10 11 12]]


In [13]:
arr_add=arr_1+arr_2
print(arr_add)

[[ 8 10 12]
 [14 16 18]]


In [14]:
arr_1*arr_2

array([[ 7, 16, 27],
       [40, 55, 72]])

In [15]:
lst_4=[2,3,4,7,8,9]
lst_5=[]
for i in lst_4:

  lst_5.append(i**2)
print(lst_5)

[4, 9, 16, 49, 64, 81]


In [16]:
arr_6=np.array(lst_4)
arr_6**2

array([ 4,  9, 16, 49, 64, 81])

In [17]:
#Reshape any array - Syntax
#Array_variable.reshape(shape)

print(arr_add)

print("--- Array after reshape ------")

print(arr_add.reshape(3,2))

[[ 8 10 12]
 [14 16 18]]
--- Array after reshape ------
[[ 8 10]
 [12 14]
 [16 18]]


In [18]:
#Flatten - It flats any dimesion array to 1D array
#Syntax     array_variable.flatten()

print(arr_3)

print("--- Array after flat operation ---")

print(arr_3.flatten())

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
--- Array after flat operation ---
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
#Array indexing and slicing
arr_8=np.array([
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20]
])
print(arr_8)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [20]:
#Accessing any element from an array
#Syntax    arr_variable[row_index_no,column_index_no]
print(arr_8[1,2])

8


In [21]:
arr_8[3,3]

19

In [22]:
#Slicing of array
#Syntax       array_variable[row_slicing,column_slicing]
arr_8[0:2,1:3] #row having index number 0 and 1 while column having index number1 and 2

array([[2, 3],
       [7, 8]])

In [23]:
#Broadcasting - It helps in the element wise operation between two arrays having different shape
matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ])
print(matrix)
print(matrix.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [24]:
vector=np.array([10,20,30])
print(vector)
print(vector.shape)

[10 20 30]
(3,)


In [25]:
arr_9=matrix+vector

In [26]:
arr_9

array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39]])