In [1]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Amit", "Riya", "John", "Sara", "Neha"],
    "Age": [18, 22, 20, 25, 19],
    "salary": [50000, 90000, 75000, 95000, 60000],
    "Travel_time": [2, 8, 5, 10, 3]
})

df

,Name,Age,salary,Travel_time
0,Amit,18,50000,2
1,Riya,22,90000,8
2,John,20,75000,5
3,Sara,25,95000,10
4,Neha,19,60000,3


In [7]:
#import standardscaler from sklearn
from sklearn.preprocessing import StandardScaler
#Create the object for StandardScaler
ss=StandardScaler()
ss

,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True


In [8]:
scaled_data=ss.fit_transform(df[["Age","salary","Travel_time"]])
scaled_data    #Array form

array([[-1.12815215, -1.39970842, -1.19734219],
       [ 0.48349378,  0.93313895,  0.79822813],
       [-0.32232919,  0.05832118, -0.19955703],
       [ 1.69222822,  1.22474487,  1.46341823],
       [-0.72524067, -0.81649658, -0.86474714]])

In [9]:
#Convert array to DataFrame
scaled_df=pd.DataFrame(scaled_data,columns=df[["Age","salary","Travel_time"]].columns)
scaled_df

,Age,salary,Travel_time
0,-1.128152,-1.399708,-1.197342
1,0.483494,0.933139,0.798228
2,-0.322329,0.058321,-0.199557
3,1.692228,1.224745,1.463418
4,-0.725241,-0.816497,-0.864747


In [10]:
#Min-Max Scaler
from sklearn.preprocessing import MinMaxScaler
#Create the object
mm=MinMaxScaler()
mm

,"feature_range feature_range: tuple (min, max), default=(0, 1)Desired range of transformed data.","(0, ...)"
,"copy copy: bool, default=TrueSet to False to perform inplace row normalization and avoid acopy (if the input is already a numpy array).",True
,"clip clip: bool, default=FalseSet to True to clip transformed values of held-out data toprovided `feature_range`.Since this parameter will clip values, `inverse_transform` may notbe able to restore the original data... note:: Setting `clip=True` does not prevent feature drift (a distribution shift between training and test data). The transformed values are clipped to the `feature_range`, which helps avoid unintended behavior in models sensitive to out-of-range inputs (e.g. linear models). Use with care, as clipping can distort the distribution of test data... versionadded:: 0.24",False


In [11]:
scaled_data_2=mm.fit_transform(df[["Age","salary","Travel_time"]])
scaled_data_2

array([[0.        , 0.        , 0.        ],
       [0.57142857, 0.88888889, 0.75      ],
       [0.28571429, 0.55555556, 0.375     ],
       [1.        , 1.        , 1.        ],
       [0.14285714, 0.22222222, 0.125     ]])

In [12]:
df_scaled_2=pd.DataFrame(scaled_data_2,columns=df[["Age","salary","Travel_time"]].columns)
df_scaled_2

,Age,salary,Travel_time
0,0.000000,0.000000,0.000
1,0.571429,0.888889,0.750
2,0.285714,0.555556,0.375
3,1.000000,1.000000,1.000
4,0.142857,0.222222,0.125


In [13]:
from sklearn.preprocessing import Normalizer

In [15]:
#Create the object
ns=Normalizer()
ns

,"norm norm: {'l1', 'l2', 'max'}, default='l2'The norm to use to normalize each non zero sample. If norm='max'is used, values will be rescaled by the maximum of the absolutevalues.",'l2'
,"copy copy: bool, default=TrueSet to False to perform inplace row normalization and avoid acopy (if the input is already a numpy array or a scipy.sparseCSR matrix).",True


In [16]:
scaled_data_3=ns.fit_transform(df[["Age","salary","Travel_time"]])
scaled_data_3

array([[3.59999976e-04, 9.99999934e-01, 3.99999974e-05],
       [2.44444436e-04, 9.99999966e-01, 8.88888859e-05],
       [2.66666657e-04, 9.99999962e-01, 6.66666641e-05],
       [2.63157884e-04, 9.99999960e-01, 1.05263154e-04],
       [3.16666650e-04, 9.99999949e-01, 4.99999974e-05]])

In [22]:
df_scaled_3=pd.DataFrame(scaled_data_3, columns=df[["Age","salary","Travel_time"]].columns)
df_scaled_3
                    

,Age,salary,Travel_time
0,0.000360,1.0,0.000040
1,0.000244,1.0,0.000089
2,0.000267,1.0,0.000067
3,0.000263,1.0,0.000105
4,0.000317,1.0,0.000050


In [23]:
from sklearn.preprocessing import RobustScaler
#Create the object
rb=RobustScaler()
rb

,"with_centering with_centering: bool, default=TrueIf `True`, center the data before scaling.This will cause :meth:`transform` to raise an exception when attemptedon sparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_scaling with_scaling: bool, default=TrueIf `True`, scale the data to interquartile range.",True
,"quantile_range quantile_range: tuple (q_min, q_max), 0.0 < q_min < q_max < 100.0, default=(25.0, 75.0)Quantile range used to calculate `scale_`. By default this is equal tothe IQR, i.e., `q_min` is the first quantile and `q_max` is the thirdquantile... versionadded:: 0.18","(25.0, ...)"
,"copy copy: bool, default=TrueIf `False`, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"unit_variance unit_variance: bool, default=FalseIf `True`, scale data so that normally distributed features have avariance of 1. In general, if the difference between the x-values of`q_max` and `q_min` for a standard normal distribution is greaterthan 1, the dataset will be scaled down. If less than 1, the datasetwill be scaled up... versionadded:: 0.24",False


In [24]:
scaled_data_4=rb.fit_transform(df[["Age","salary","Travel_time"]])
scaled_data_4

array([[-0.66666667, -0.83333333, -0.6       ],
       [ 0.66666667,  0.5       ,  0.6       ],
       [ 0.        ,  0.        ,  0.        ],
       [ 1.66666667,  0.66666667,  1.        ],
       [-0.33333333, -0.5       , -0.4       ]])

In [25]:
#Convert the scaled data to dataframe
df_scaled_4=pd.DataFrame(scaled_data_4,columns=df[["Age","salary","Travel_time"]].columns)
df_scaled_4

,Age,salary,Travel_time
0,-0.666667,-0.833333,-0.6
1,0.666667,0.500000,0.6
2,0.000000,0.000000,0.0
3,1.666667,0.666667,1.0
4,-0.333333,-0.500000,-0.4


In [26]:
#Outlier capping - Instead of removing the outlier we can cap the outlier value within the data range
#IQR = Q3-Q1
#upper_fence=Q3+1.5*IQR
#lower_fence=Q1-1.5*IQR

import pandas as pd
data={
    "Name":["Priyanka","Sudeep","Sujoy","Anuska"],
    "Salary":[30000,28000,32000,6768778778778]      #salary contains the outliers
}

df6=pd.DataFrame(data)
df6

,Name,Salary
0,Priyanka,30000
1,Sudeep,28000
2,Sujoy,32000
3,Anuska,6768778778778


In [27]:
import numpy as np
Q1=np.percentile(df6["Salary"],25)
Q3=np.percentile(df6["Salary"],75)
IQR=Q3-Q1
upper_fence=Q3+1.5*IQR
lower_fence=Q1-1.5*IQR
print(Q1,Q3,IQR,upper_fence,lower_fence)

29500.0 1692194718694.5 1692194689194.5 4230486752486.25 -2538292004291.75


In [28]:
#cap the salary
df6["Salary"]=np.where(df6["Salary"]>upper_fence,upper_fence,df6["Salary"])
df6["Salary"]=np.where(df6["Salary"]<lower_fence,lower_fence,df6["Salary"])
df6

,Name,Salary
0,Priyanka,3.000000e+04
1,Sudeep,2.800000e+04
2,Sujoy,3.200000e+04
3,Anuska,4.230487e+12


In [29]:
#Option_2
df6["Salary_cap"]=np.clip(df6["Salary"],lower_fence,upper_fence)
df6

,Name,Salary,Salary_cap
0,Priyanka,3.000000e+04,3.000000e+04
1,Sudeep,2.800000e+04,2.800000e+04
2,Sujoy,3.200000e+04,3.200000e+04
3,Anuska,4.230487e+12,4.230487e+12
